plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/victorparadinas/Desktop/T A K E Y S  :  F O C U S /FOCUS/WEB"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]